/* RISE Sports service worker — GENERATED by build.js. Do not edit.
   Rebuild with: node build.js
   Cache is keyed to the build hash, so a new build always supersedes the old. */
const CACHE = "rise-sports-23d7755cd1d0";
const ASSETS = [
  "./",
  "./rise-sports.html",
  "./manifest.webmanifest",
  "./icons/icon-192.png",
  "./icons/icon-512.png",
  "./icons/icon-512-maskable.png",
  "./icons/apple-touch-icon.png"
];

self.addEventListener("install", e => {
  /* Added one at a time: cache.addAll rejects the whole batch if a single
     entry 404s, which would leave the app with no offline copy at all. */
  e.waitUntil(caches.open(CACHE)
    .then(c => Promise.all(ASSETS.map(u => c.add(u).catch(() => {}))))
    .then(() => self.skipWaiting()));
});

self.addEventListener("activate", e => {
  e.waitUntil(caches.keys()
    .then(keys => Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k))))
    .then(() => self.clients.claim()));
});

self.addEventListener("fetch", e => {
  const req = e.request;
  if (req.method !== "GET") return;

  /* The page itself is network-first: a returning user should get the new
     build when they have signal, and the cached one when they do not. */
  if (req.mode === "navigate") {
    e.respondWith(
      fetch(req)
        .then(res => {
          const copy = res.clone();
          caches.open(CACHE).then(c => c.put(req, copy)).catch(() => {});
          return res;
        })
        .catch(() => caches.match(req).then(r => r || caches.match("./rise-sports.html")))
    );
    return;
  }

  /* Everything else (icons, manifest) is content-addressed by build hash,
     so cache-first is safe and keeps the app instant on a bad connection. */
  e.respondWith(caches.match(req).then(r => r || fetch(req)));
});
